language: node_js
node_js:
  - "11.9.0"
dist: xenial
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_TLS_VERIFY="1"
    - DOCKER_HOST="tcp://104.42.146.209:2376"
    - DOCKER_CERT_PATH="$TRAVIS_BUILD_DIR/azure"
    - DOCKER_MACHINE_NAME="group-2"

script:
  - cd ./server && npm install
  - npm test
  - cd ..
  - docker-compose  --file docker-compose.prod.yml build

deploy:
  skip_cleanup: true
  provider: script
  script: docker-compose --file docker-compose.prod.yml up -d --remove-orphans
  on:
    branch: master
